// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6ARbScnxsqPPNlFqAQXc0rQWBiKNVGU',
    appId: '1:394370264308:web:b6b90b19c0337d523cc2a1',
    messagingSenderId: '394370264308',
    projectId: 'porto-space-app',
    authDomain: 'porto-space-app.firebaseapp.com',
    storageBucket: 'porto-space-app.appspot.com',
    measurementId: 'G-H194EK7KHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBG-rp2_-Qgyq0fNahPsSL-rPYb2gjZOA',
    appId: '1:394370264308:android:b552e65611fed7483cc2a1',
    messagingSenderId: '394370264308',
    projectId: 'porto-space-app',
    storageBucket: 'porto-space-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT7m4Bc20Ax3PLKXe0Di9T7rc7qrObk_4',
    appId: '1:394370264308:ios:008784a4630b197e3cc2a1',
    messagingSenderId: '394370264308',
    projectId: 'porto-space-app',
    storageBucket: 'porto-space-app.appspot.com',
    iosClientId: '394370264308-vg6btuq7258tufms6bcdklo9bipi8tla.apps.googleusercontent.com',
    iosBundleId: 'com.example.portoSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT7m4Bc20Ax3PLKXe0Di9T7rc7qrObk_4',
    appId: '1:394370264308:ios:008784a4630b197e3cc2a1',
    messagingSenderId: '394370264308',
    projectId: 'porto-space-app',
    storageBucket: 'porto-space-app.appspot.com',
    iosClientId: '394370264308-vg6btuq7258tufms6bcdklo9bipi8tla.apps.googleusercontent.com',
    iosBundleId: 'com.example.portoSpace',
  );
}
